In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv('/content/Placement_Data_Full_Class.csv')

In [ ]:
dataset.describe()

sl_no       ssc_p  ...       mba_p         salary
count  215.000000  215.000000  ...  215.000000     148.000000
mean   108.000000   67.303395  ...   62.278186  288655.405405
std     62.209324   10.827205  ...    5.833385   93457.452420
min      1.000000   40.890000  ...   51.210000  200000.000000
25%     54.500000   60.600000  ...   57.945000  240000.000000
50%    108.000000   67.000000  ...   62.000000  265000.000000
75%    161.500000   75.700000  ...   66.255000  300000.000000
max    215.000000   89.400000  ...   77.890000  940000.000000

[8 rows x 7 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [ ]:
 dataset.head(10)

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0      1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1      2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2      3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3      4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4      5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
5      6      M  55.00   Others  ...         Mkt&Fin  51.58  Not Placed       NaN
6      7      F  46.00   Others  ...         Mkt&Fin  53.29  Not Placed       NaN
7      8      M  82.00  Central  ...         Mkt&Fin  62.14      Placed  252000.0
8      9      M  73.00  Central  ...         Mkt&Fin  61.29      Placed  231000.0
9     10      M  58.00  Central  ...         Mkt&Fin  52.21  Not Placed       NaN

[10 rows x 15 columns]

In [ ]:
dataset.tail()

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
210    211      M   80.6   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M   58.0   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M   67.0   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F   74.0   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M   62.0  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[5 rows x 15 columns]

In [ ]:
dataset[dataset==np.inf]=np.nan
dataset.fillna(dataset.mean(),inplace=True)

In [ ]:
def replace_missing_value(dataset,number_feautures):
  imputer = imputer(strategy = "median")
  dataset_num = dataset[number_feautures]
  imputer.fit(dataset_num)
  x = imputer.transform(dataset_num)
  res_def = pd.DataFrame(x , columns=dataset_num.columns)
  return res_def

In [ ]:
number_features = ['salary']

In [ ]:
dataset

sl_no gender  ssc_p  ...  mba_p      status         salary
0        1      M  67.00  ...  58.80      Placed  270000.000000
1        2      M  79.33  ...  66.28      Placed  200000.000000
2        3      M  65.00  ...  57.80      Placed  250000.000000
3        4      M  56.00  ...  59.43  Not Placed  288655.405405
4        5      M  85.80  ...  55.50      Placed  425000.000000
..     ...    ...    ...  ...    ...         ...            ...
210    211      M  80.60  ...  74.49      Placed  400000.000000
211    212      M  58.00  ...  53.62      Placed  275000.000000
212    213      M  67.00  ...  69.72      Placed  295000.000000
213    214      F  74.00  ...  60.23      Placed  204000.000000
214    215      M  62.00  ...  60.22  Not Placed  288655.405405

[215 rows x 15 columns]

In [ ]:
dataset['gender'].unique()

array(['M', 'F'], dtype=object)

In [ ]:
dataset.isnull()

sl_no  gender  ssc_p  ssc_b  ...  specialisation  mba_p  status  salary
0    False   False  False  False  ...           False  False   False   False
1    False   False  False  False  ...           False  False   False   False
2    False   False  False  False  ...           False  False   False   False
3    False   False  False  False  ...           False  False   False   False
4    False   False  False  False  ...           False  False   False   False
..     ...     ...    ...    ...  ...             ...    ...     ...     ...
210  False   False  False  False  ...           False  False   False   False
211  False   False  False  False  ...           False  False   False   False
212  False   False  False  False  ...           False  False   False   False
213  False   False  False  False  ...           False  False   False   False
214  False   False  False  False  ...           False  False   False   False

[215 rows x 15 columns]

In [ ]:
dataset.drop('salary',axis =1)

sl_no gender  ssc_p    ssc_b  ...  etest_p specialisation  mba_p      status
0        1      M  67.00   Others  ...     55.0         Mkt&HR  58.80      Placed
1        2      M  79.33  Central  ...     86.5        Mkt&Fin  66.28      Placed
2        3      M  65.00  Central  ...     75.0        Mkt&Fin  57.80      Placed
3        4      M  56.00  Central  ...     66.0         Mkt&HR  59.43  Not Placed
4        5      M  85.80  Central  ...     96.8        Mkt&Fin  55.50      Placed
..     ...    ...    ...      ...  ...      ...            ...    ...         ...
210    211      M  80.60   Others  ...     91.0        Mkt&Fin  74.49      Placed
211    212      M  58.00   Others  ...     74.0        Mkt&Fin  53.62      Placed
212    213      M  67.00   Others  ...     59.0        Mkt&Fin  69.72      Placed
213    214      F  74.00   Others  ...     70.0         Mkt&HR  60.23      Placed
214    215      M  62.00  Central  ...     89.0         Mkt&HR  60.22  Not Placed

[215 rows x 14 columns]

In [ ]:
from sklearn import preprocessing

In [ ]:
label_encoder = preprocessing.LabelEncoder()

In [ ]:
dataset['gender'] = label_encoder.fit_transform(dataset['gender'])

In [ ]:
dataset['gender'].unique()

array([1, 0])

In [ ]:
dataset['ssc_b'].unique()

array(['Others', 'Central'], dtype=object)

In [ ]:
dataset['ssc_b'] = label_encoder.fit_transform(dataset['ssc_b'])

In [ ]:
dataset['ssc_b'].unique()

array([1, 0])

In [ ]:
dataset['hsc_b'].unique()

array(['Others', 'Central'], dtype=object)

In [ ]:
dataset['hsc_b'] = label_encoder.fit_transform(dataset['hsc_b'])

In [ ]:
dataset['hsc_b'].unique()

array([1, 0])

In [ ]:
dataset['hsc_s'].unique

<bound method Series.unique of 0      Commerce
1       Science
2          Arts
3       Science
4      Commerce
         ...   
210    Commerce
211     Science
212    Commerce
213    Commerce
214     Science
Name: hsc_s, Length: 215, dtype: object>

In [ ]:
dataset['hsc_s'] = label_encoder.fit_transform(dataset['hsc_s'])

In [ ]:
dataset['hsc_s'].unique()

array([1, 2, 0])

In [ ]:
dataset['degree_t'].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [ ]:
dataset['degree_t'] = label_encoder.fit_transform(dataset['degree_t'])

In [ ]:
dataset['degree_t'].unique()

array([2, 0, 1])

In [ ]:
dataset['workex'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
dataset['workex'] = label_encoder.fit_transform(dataset['workex'])

In [ ]:
dataset['workex'].unique()


array([0, 1])

In [ ]:
dataset['specialisation'].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [ ]:
dataset['specialisation'] = label_encoder.fit_transform(dataset['specialisation'])

In [ ]:
dataset['specialisation'].unique()

array([1, 0])

In [ ]:
dataset['status'] = label_encoder.fit_transform(dataset['status'])

In [ ]:
dataset['status'].unique()

array([1, 0])

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    int64  
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    int64  
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    int64  
 6   hsc_s           215 non-null    int64  
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    int64  
 9   workex          215 non-null    int64  
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    int64  
 12  mba_p           215 non-null    float64
 13  status          215 non-null    int64  
 14  salary          215 non-null    float64
dtypes: float64(6), int64(9)
memory usage: 25.3 KB


In [ ]:
x = dataset.iloc[: , :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
x

array([[  1.  ,   1.  ,  67.  , ...,   1.  ,  58.8 ,   1.  ],
       [  2.  ,   1.  ,  79.33, ...,   0.  ,  66.28,   1.  ],
       [  3.  ,   1.  ,  65.  , ...,   0.  ,  57.8 ,   1.  ],
       ...,
       [213.  ,   1.  ,  67.  , ...,   0.  ,  69.72,   1.  ],
       [214.  ,   0.  ,  74.  , ...,   1.  ,  60.23,   1.  ],
       [215.  ,   1.  ,  62.  , ...,   1.  ,  60.22,   0.  ]])

In [ ]:
y

array([270000.        , 200000.        , 250000.        , 288655.40540541,
       425000.        , 288655.40540541, 288655.40540541, 252000.        ,
       231000.        , 288655.40540541, 260000.        , 250000.        ,
       288655.40540541, 218000.        , 288655.40540541, 200000.        ,
       300000.        , 288655.40540541, 288655.40540541, 236000.        ,
       265000.        , 393000.        , 360000.        , 300000.        ,
       360000.        , 288655.40540541, 240000.        , 265000.        ,
       350000.        , 288655.40540541, 250000.        , 288655.40540541,
       278000.        , 260000.        , 288655.40540541, 300000.        ,
       288655.40540541, 320000.        , 240000.        , 411000.        ,
       287000.        , 288655.40540541, 288655.40540541, 300000.        ,
       200000.        , 288655.40540541, 288655.40540541, 204000.        ,
       250000.        , 288655.40540541, 200000.        , 288655.40540541,
       288655.40540541, 4

In [ ]:
dataset.head()

sl_no  gender  ssc_p  ssc_b  ...  specialisation  mba_p  status         salary
0      1       1  67.00      1  ...               1  58.80       1  270000.000000
1      2       1  79.33      0  ...               0  66.28       1  200000.000000
2      3       1  65.00      0  ...               0  57.80       1  250000.000000
3      4       1  56.00      0  ...               1  59.43       0  288655.405405
4      5       1  85.80      0  ...               0  55.50       1  425000.000000

[5 rows x 15 columns]

In [ ]:
dataset.tail()

sl_no  gender  ssc_p  ssc_b  ...  specialisation  mba_p  status         salary
210    211       1   80.6      1  ...               0  74.49       1  400000.000000
211    212       1   58.0      1  ...               0  53.62       1  275000.000000
212    213       1   67.0      1  ...               0  69.72       1  295000.000000
213    214       0   74.0      1  ...               1  60.23       1  204000.000000
214    215       1   62.0      0  ...               1  60.22       0  288655.405405

[5 rows x 15 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x ,y, test_size=0.25)


In [ ]:
print(len(x_train))

161


In [ ]:
 print(len(x_test))
 print(len(y_train))
 print(len(y_test))

54
161
54


In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
sc=MinMaxScaler()

In [ ]:
sc.fit(dataset)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
sc=sc.transform(dataset)

In [ ]:
sc.round(2)

array([[0.  , 1.  , 0.54, ..., 0.28, 1.  , 0.09],
       [0.  , 1.  , 0.79, ..., 0.56, 1.  , 0.  ],
       [0.01, 1.  , 0.5 , ..., 0.25, 1.  , 0.07],
       ...,
       [0.99, 1.  , 0.54, ..., 0.69, 1.  , 0.13],
       [1.  , 0.  , 0.68, ..., 0.34, 1.  , 0.01],
       [1.  , 1.  , 0.44, ..., 0.34, 0.  , 0.12]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
t_train =y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [ ]:
x_std_train = x_sc.fit_transform(x_train)
y_std_train = y_sc.fit_transform(t_train)



In [ ]:
x_std_test = x_sc.fit_transform(x_test)
y_std_test = y_sc.fit_transform(t_test)



In [ ]:
x_test[:10,5:]

array([[ 0.  ,  1.  , 69.  ,  0.  ,  0.  , 84.  ,  0.  , 58.31,  1.  ],
       [ 1.  ,  1.  , 70.67,  0.  ,  0.  , 89.  ,  0.  , 60.39,  1.  ],
       [ 0.  ,  1.  , 60.  ,  0.  ,  1.  , 62.  ,  1.  , 60.85,  1.  ],
       [ 1.  ,  1.  , 67.  ,  0.  ,  0.  , 72.15,  0.  , 63.08,  1.  ],
       [ 0.  ,  1.  , 54.  ,  0.  ,  0.  , 72.  ,  1.  , 55.41,  0.  ],
       [ 1.  ,  1.  , 65.  ,  0.  ,  1.  , 95.46,  0.  , 62.16,  1.  ],
       [ 0.  ,  2.  , 66.  ,  2.  ,  0.  , 75.  ,  1.  , 67.99,  0.  ],
       [ 0.  ,  0.  , 64.  ,  0.  ,  0.  , 75.  ,  0.  , 57.8 ,  1.  ],
       [ 1.  ,  0.  , 61.  ,  0.  ,  0.  , 60.  ,  0.  , 58.52,  0.  ],
       [ 1.  ,  1.  , 65.  ,  0.  ,  0.  , 62.  ,  0.  , 56.81,  1.  ]])

In [ ]:
x_train

array([[ 70.  ,   1.  ,  73.  , ...,   0.  ,  68.07,   1.  ],
       [189.  ,   1.  ,  61.8 , ...,   0.  ,  56.13,   0.  ],
       [ 22.  ,   0.  ,  79.  , ...,   0.  ,  69.06,   1.  ],
       ...,
       [ 47.  ,   0.  ,  70.89, ...,   1.  ,  71.63,   0.  ],
       [142.  ,   1.  ,  66.  , ...,   1.  ,  61.9 ,   0.  ],
       [ 45.  ,   0.  ,  77.  , ...,   0.  ,  69.7 ,   1.  ]])

In [ ]:
y_train

array([275000.        , 288655.40540541, 393000.        , 240000.        ,
       288655.40540541, 300000.        , 275000.        , 400000.        ,
       288655.40540541, 300000.        , 218000.        , 240000.        ,
       336000.        , 400000.        , 250000.        , 216000.        ,
       288655.40540541, 500000.        , 200000.        , 270000.        ,
       250000.        , 288655.40540541, 288655.40540541, 288655.40540541,
       288655.40540541, 200000.        , 300000.        , 250000.        ,
       288655.40540541, 288655.40540541, 231000.        , 275000.        ,
       288655.40540541, 220000.        , 500000.        , 285000.        ,
       250000.        , 270000.        , 288655.40540541, 288655.40540541,
       276000.        , 288655.40540541, 288655.40540541, 300000.        ,
       360000.        , 210000.        , 250000.        , 940000.        ,
       210000.        , 288655.40540541, 288655.40540541, 210000.        ,
       300000.        , 2

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [ ]:
m_reg = LinearRegression()
p_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
r_reg = RandomForestRegressor(n_estimators=250)
s_reg =SVR()

In [ ]:
x_poly =PolynomialFeatures(degree=3)
x_poly = x_poly.fit_transform(x_train)

In [ ]:
m_reg.fit(x_train,y_train)
p_reg.fit(x_poly,y_train)
d_reg.fit(x_train,y_train)
r_reg.fit(x_train,y_train)
s_reg.fit(x_std_train,y_std_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
temp = PolynomialFeatures(degree=3)
temp = temp.fit_transform(x_test)

In [ ]:
m_pred = m_reg.predict(x_test)
p_pred = p_reg.predict(temp)
d_pred = d_reg.predict(x_test)
r_pred = r_reg.predict(x_test)
s_pred = s_reg.predict(x_std_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
m= r2_score(y_test,m_pred)
p = r2_score(y_test , p_pred)
d  = r2_score(y_test,d_pred)
r = r2_score(y_test,r_pred)
s = r2_score(y_std_test,s_pred)

In [ ]:
print(m , p , d, r, s)

0.028276386442255053 -44.909747151200925 -0.23484499669563053 -0.02631857517508851 -0.03822974467048357


ValueError: ignored