<a href="https://colab.research.google.com/github/1ah17cs049/Intro-to-Ml-R.-Akhila/blob/master/Winequality_red_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv('/content/winequality-red.csv')

In [ ]:
dataset.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [ ]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
winered = LabelEncoder()

In [ ]:
dataset['quality'] = winered.fit_transform(dataset['quality'])

In [ ]:
dataset['quality'].value_counts()

2    681
3    638
4    199
1     53
5     18
0     10
Name: quality, dtype: int64

In [ ]:
x = dataset.drop('quality',axis = 1).values
y = dataset.iloc[:,-1].values

In [ ]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y

array([2, 2, 2, ..., 3, 2, 3])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.2)

In [ ]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

1279
320
1279
320


In [ ]:
from sklearn.preprocessing import MinMaxScaler


In [ ]:
sc = MinMaxScaler()

In [ ]:
sc.fit(dataset)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
sc = sc.transform(dataset)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.25)

In [ ]:
x_sc = StandardScaler()
y_sc = StandardScaler()


In [ ]:
x_std_train = x_sc.fit_transform(x_train)
y_std_train = x_sc.fit_transform(t_train)

In [ ]:
x_std_test = x_sc.transform(x_test)
y_std_test = x_sc.transform(t_test)

In [ ]:
x_test[:10,5:]

array([[ 41.     , 110.     ,   0.9982 ,   3.08   ,   0.61   ,   9.2    ],
       [ 10.     ,  31.     ,   0.99656,   3.25   ,   0.5    ,   9.8    ],
       [ 10.     ,  22.     ,   0.9976 ,   3.22   ,   0.44   ,   9.6    ],
       [ 19.     ,  47.     ,   1.0003 ,   3.26   ,   1.11   ,  11.     ],
       [ 12.     ,  42.     ,   1.0004 ,   3.16   ,   0.61   ,  10.3    ],
       [ 13.     ,  28.     ,   0.99712,   3.25   ,   0.62   ,  10.     ],
       [  6.     ,  15.     ,   0.9973 ,   3.09   ,   0.66   ,  11.8    ],
       [  6.     ,  12.     ,   0.99495,   3.44   ,   0.72   ,  11.5    ],
       [ 13.     ,  54.     ,   0.99724,   3.36   ,   0.54   ,  10.1    ],
       [ 17.     ,  31.     ,   0.9964 ,   3.33   ,   0.56   ,  10.     ]])

Finding Accurate score Using **RandomForest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
r_cla = RandomForestClassifier()

In [ ]:
r_cla.fit(x_train , y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
r_pred = r_cla.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
r_c = confusion_matrix(y_test , r_pred)

In [ ]:
print(r_c)

[[  0   0   2   0   0   0]
 [  0   0   6   2   1   0]
 [  0   0 101  29   2   0]
 [  0   0  30  96   5   0]
 [  0   0   5  20  19   0]
 [  0   0   0   1   0   1]]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
r_acc = accuracy_score(y_test , r_pred)

In [ ]:
print('Random Forest:' + str(r_acc))

Random Forest:0.678125


Therefore RandomForest Classifier Model has got highest accuracy

Thankyou